FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

# Geen EXPOSE nodig – nginx spreekt intern met deze container
CMD ["python", "app.py"]
