version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - appnet

  reverse-proxy:
    build: ./reverse-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - appnet

networks:
  appnet:
